In [104]:
import pandas as pd

In [105]:
'''
# Created genres.txt file from ratings.txt file by doing required processing (Eg: 0 -> Children, 1 -> GraphicComic)

replacement_mapping = {
    0: 'children',
    1: 'graphiccomics',
    2: 'paranormalfantasy',
    3: 'historybiography',
    4: 'crimemysterythriller',
    5: 'poetry',
    6: 'romance',
    7: 'youngadult',
}

with open('score.txt', 'r') as infile, open('genres.txt', 'w') as outfile:
    for line in infile:
        try:
            value = int(line.strip())
            replaced_value = replacement_mapping.get(value, str(value))
        except ValueError:
            replaced_value = line.strip()

        outfile.write(replaced_value + '\n')

'''

"\nreplacement_mapping = {\n    0: 'children',\n    1: 'graphiccomics',\n    2: 'paranormalfantasy',\n    3: 'historybiography',\n    4: 'crimemysterythriller',\n    5: 'poetry',\n    6: 'romance',\n    7: 'youngadult',\n}\n\nwith open('score.txt', 'r') as infile, open('genres.txt', 'w') as outfile:\n    for line in infile:\n        try:\n            value = int(line.strip())\n            replaced_value = replacement_mapping.get(value, str(value))\n        except ValueError:\n            replaced_value = line.strip()\n\n        outfile.write(replaced_value + '\n')\n\n"

In [106]:
# Converts the txt file to csv file where the fields are: Name, Genre, Description

with open('texts.txt', 'r', encoding='utf-8') as file:
    lines = file.readlines()

names = [line.split('.')[0].strip() for line in lines]
descriptions = [line.split('.', 1)[1].strip() for line in lines]

with open('genres.txt', 'r', encoding='utf-8') as genre_file:
    genre = [genre.strip() for genre in genre_file.readlines()]

df = pd.DataFrame({'Name': names, 'Genre': genre, 'Description': descriptions})
df.to_csv('books.csv', index=False)

In [107]:
# Stored the dataset csv books.csv in a pandas DataFrame books

books = pd.read_csv('books.csv');
books.head()

,Name,Genre,Description
0,dog heaven,children,in newbery medalist cynthia rylant's classic b...
1,the saturdays,children,meet the melendys! the four melendy children l...
2,the legend of rock paper scissors,children,you've played the game. now read the legend of...
3,leo the littlest seahorse,children,"in the warm waters of the coral reef, one hund..."
4,miss mary mack,children,everyone knows some version of this popular ch...

In [108]:
books.isnull().sum()                                              # checks for total number of null values
books.dropna(inplace=True)                                        # drops null values
books.duplicated().sum()                                          # checks for duplicate values 
books = books.drop_duplicates(subset=['Name', 'Description'])     # drops duplicate values

In [109]:
# Converts the string to a list for better processing

books['Genre'] = books['Genre'].apply(lambda x:x.split())
books['Description'] = books['Description'].apply(lambda X:X.split())
books.head()

,Name,Genre,Description
0,dog heaven,[children],"[in, newbery, medalist, cynthia, rylant's, cla..."
1,the saturdays,[children],"[meet, the, melendys!, the, four, melendy, chi..."
2,the legend of rock paper scissors,[children],"[you've, played, the, game., now, read, the, l..."
3,leo the littlest seahorse,[children],"[in, the, warm, waters, of, the, coral, reef,,..."
4,miss mary mack,[children],"[everyone, knows, some, version, of, this, pop..."

In [110]:
# Creates a new column Tags which is a combination of two existing columns - Description, Genre

books['Tags'] = books['Description'] + books['Genre']
books['Tags'].head()

0    [in, newbery, medalist, cynthia, rylant's, cla...
1    [meet, the, melendys!, the, four, melendy, chi...
2    [you've, played, the, game., now, read, the, l...
3    [in, the, warm, waters, of, the, coral, reef,,...
4    [everyone, knows, some, version, of, this, pop...
Name: Tags, dtype: object

In [111]:
# Creates a new DataFrame called modifies_books_data by selecting the columns Name, Genre, Description from existing DataFrame Books

modified_books_data = books[['Name', 'Genre', 'Tags']]
modified_books_data['Name'] = modified_books_data['Name'].apply(lambda x: x.title())        # Converts font of Name to Title Case
modified_books_data['Tags'] = modified_books_data['Tags'].apply(lambda x:" ".join(x))       # Converts list to a single string
modified_books_data['Genre'] = modified_books_data['Genre'].apply(lambda x:" ".join(x))     # Converts list to a single string
modified_books_data['Tags'] = modified_books_data['Tags'].apply(lambda x:x.lower())         # Converts font style of Tags to be lower
modified_books_data.head()

C:\Users\Kushal Gupta\AppData\Local\Temp\ipykernel_24200\308918195.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modified_books_data['Name'] = modified_books_data['Name'].apply(lambda x: x.title())
C:\Users\Kushal Gupta\AppData\Local\Temp\ipykernel_24200\308918195.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modified_books_data['Tags'] = modified_books_data['Tags'].apply(lambda x:" ".join(x))
C:\Users\Kushal Gupta\AppData\Local\Temp\ipykernel_24200\308918195.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modified_books_data['Genre'] = modified_books_data['Genre'].apply(lambda x:" ".join(x))
C:\Users\Kushal Gupta\AppData\Local\Temp\ipykernel_24200\308918195.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modified_books_data['Tags'] = modified_books_data['Tags'].apply(lambda x:x.lower())

,Name,Genre,Tags
0,Dog Heaven,children,in newbery medalist cynthia rylant's classic b...
1,The Saturdays,children,meet the melendys! the four melendy children l...
2,The Legend Of Rock Paper Scissors,children,you've played the game. now read the legend of...
3,Leo The Littlest Seahorse,children,"in the warm waters of the coral reef, one hund..."
4,Miss Mary Mack,children,everyone knows some version of this popular ch...

In [112]:
# A UDF to stem the data (Stemming - Text normalization Technique)
# Eg: running - run

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

modified_books_data['Tags'] = modified_books_data['Tags'].apply(stem)

C:\Users\Kushal Gupta\AppData\Local\Temp\ipykernel_24200\1871308213.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modified_books_data['Tags'] = modified_books_data['Tags'].apply(stem)

In [ ]:
# Converts collection of text documents into matrices

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

# Creates vector relation between the column Tags

vectors = cv.fit_transform(modified_books_data['Tags']).toarray()
cv.get_feature_names_out()

In [114]:
# Finds the distance between the vectors with each other

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [115]:
# A UDF which takes name of book as an argument / parameter and returns names of books which are closest to the provided book based on similarity matrix

def recommend(book):
    book_index = modified_books_data[modified_books_data['Name'] == book].index[0]
    book_genre = modified_books_data.iloc[book_index]['Genre']

    same_genre_books = modified_books_data[modified_books_data['Genre'] == book_genre]

    distances = similarity[book_index][same_genre_books.index]
    books_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    for i in books_list:
        print(same_genre_books.iloc[i[0]].Name)

In [116]:
recommend('Dog Heaven')

The Detective Dog
Just Like Heaven
The Mystery At The Dog Show (The Boxcar Children, #35)
My Pet Book
The Sound Of Colors: A Journey Of The Imagination

In [117]:
# Importing modified_books_data DataFrame (in the form of dictionary for ease) and similarity matrix

import pickle
pickle.dump(modified_books_data.to_dict(), open('book_dict.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))